backend/lib/azimutt_web/router.ex
defmodule AzimuttWeb.Router do
  use AzimuttWeb, :router
  import AzimuttWeb.UserAuth
  alias AzimuttWeb.Plugs.AllowCrossOriginIframe

  pipeline :browser_no_csrf_protection do
    plug(Ueberauth)
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {AzimuttWeb.LayoutView, :root_hfull})
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
    plug(:fetch_clever_cloud_resource)
    plug(:fetch_heroku_resource)
    plug(:track_attribution)
  end

  pipeline :browser do
    plug(:browser_no_csrf_protection)
    plug(:protect_from_forgery)
  end

  pipeline :api do
    plug(CORSPlug)
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:fetch_current_user)
    plug(:fetch_clever_cloud_resource)
    plug(:fetch_heroku_resource)
  end

  pipeline(:website_root_layout, do: plug(:put_root_layout, {AzimuttWeb.LayoutView, "root_website.html"}))
  pipeline(:hfull_root_layout, do: plug(:put_root_layout, {AzimuttWeb.LayoutView, "root_hfull.html"}))
  pipeline(:organization_root_layout, do: plug(:put_root_layout, {AzimuttWeb.LayoutView, "root_organization.html"}))
  pipeline(:admin_root_layout, do: plug(:put_root_layout, {AzimuttWeb.LayoutView, "root_admin.html"}))
  pipeline(:elm_root_layout, do: plug(:put_root_layout, {AzimuttWeb.LayoutView, "root_elm.html"}))
  pipeline(:user_settings_root_layout, do: plug(:put_root_layout, {AzimuttWeb.LayoutView, "root_user_settings.html"}))
  pipeline(:empty_layout, do: plug(:put_layout, {AzimuttWeb.LayoutView, "empty.html"}))

  # public routes
  scope "/", AzimuttWeb do
    pipe_through([:browser, :website_root_layout])
    get("/", WebsiteController, :index)
    get("/last", WebsiteController, :last)
    get("/use-cases", WebsiteController, :use_cases_index)
    get("/use-cases/:use_case_id", WebsiteController, :use_cases_show)
    get("/features", WebsiteController, :features_index)
    get("/features/:feature_id", WebsiteController, :features_show)
    get("/pricing", WebsiteController, :pricing)
    get("/blog", BlogController, :index)
    if Azimutt.Application.env() == :dev, do: get("/blog/cards", BlogController, :cards)
    get("/blog/:article_id", BlogController, :show)
    get("/gallery", GalleryController, :index)
    get("/gallery/:slug", GalleryController, :show)
    get("/logout", UserSessionController, :delete)
    delete("/logout", UserSessionController, :delete)
    get("/sitemap.xml", SitemapController, :index)
    get("/terms", WebsiteController, :terms)
    get("/privacy", WebsiteController, :privacy)
  end

  # auth routes
  scope "/", AzimuttWeb do
    pipe_through([:browser, :redirect_if_user_is_authed, :hfull_root_layout])
    get("/auth/:provider", UserOauthController, :request)
    get("/auth/:provider/callback", UserOauthController, :callback)
    get("/register", UserRegistrationController, :new)
    post("/register", UserRegistrationController, :create)
    get("/login", UserSessionController, :new)
    post("/login", UserSessionController, :create)
    get("/reset-password", UserResetPasswordController, :new)
    post("/reset-password", UserResetPasswordController, :create)
    get("/reset-password/:token", UserResetPasswordController, :edit)
    put("/reset-password/:token", UserResetPasswordController, :update)
  end

  # authed dashboard routes
  scope "/", AzimuttWeb do
    pipe_through([:browser, :require_authed_user, :organization_root_layout])
    get("/home", UserDashboardController, :index)
    get("/login/redirect", UserSessionController, :redirect_to)

    scope "/email-confirm" do
      pipe_through([:hfull_root_layout])
      get("/", UserConfirmationController, :new)
      post("/", UserConfirmationController, :create)
      get("/:token", UserConfirmationController, :confirm)
    end

    scope "/onboarding" do
      pipe_through([:hfull_root_layout, :empty_layout])
      get("/", UserOnboardingController, :index)
      get("/welcome", UserOnboardingController, :welcome)
      post("/welcome", UserOnboardingController, :welcome_next)
      get("/explore-or-design", UserOnboardingController, :explore_or_design)
      post("/explore-or-design", UserOnboardingController, :explore_or_design_next)
      get("/solo-or-team", UserOnboardingController, :solo_or_team)
      post("/solo-or-team", UserOnboardingController, :solo_or_team_next)
      get("/role", UserOnboardingController, :role)
      post("/role", UserOnboardingController, :role_next)
      get("/about-you", UserOnboardingController, :about_you)
      put("/about-you", UserOnboardingController, :about_you_next)
      get("/about-your-company", UserOnboardingController, :about_your_company)
      put("/about-your-company", UserOnboardingController, :about_your_company_next)
      get("/plan", UserOnboardingController, :plan)
      post("/plan", UserOnboardingController, :plan_next)
      get("/discovered-azimutt", UserOnboardingController, :discovered_azimutt)
      put("/discovered-azimutt", UserOnboardingController, :discovered_azimutt_next)
      get("/previous-solutions", UserOnboardingController, :previous_solutions)
      put("/previous-solutions", UserOnboardingController, :previous_solutions_next)
      get("/keep-in-touch", UserOnboardingController, :keep_in_touch)
      put("/keep-in-touch", UserOnboardingController, :keep_in_touch_next)
      get("/community", UserOnboardingController, :community)
      post("/community", UserOnboardingController, :community_next)
      get("/finalize", UserOnboardingController, :finalize)

      if Azimutt.Application.env() == :dev, do: get("/:template", UserOnboardingController, :template)
    end

    scope "/settings" do
      pipe_through([:user_settings_root_layout, :empty_layout])
      get("/", UserSettingsController, :show)
      put("/account", UserSettingsController, :update_account)
      put("/email", UserSettingsController, :update_email)
      get("/email/:token", UserSettingsController, :confirm_update_email)
      put("/password", UserSettingsController, :update_password)
      post("/password", UserSettingsController, :set_password)
      delete("/providers/:provider", UserSettingsController, :remove_provider)
      post("/auth-tokens", UserSettingsController, :create_auth_token)
      delete("/auth-tokens/:token_id", UserSettingsController, :delete_auth_token)
    end

    resources "/organizations", OrganizationController, param: "organization_id", except: [:index] do
      get("/billing", OrganizationBillingController, :index, as: :billing)
      post("/billing/new", OrganizationBillingController, :new, as: :billing)
      post("/billing/edit", OrganizationBillingController, :edit, as: :billing)
      get("/billing/success", OrganizationBillingController, :success, as: :billing)
      get("/billing/cancel", OrganizationBillingController, :cancel, as: :billing)
      get("/members", OrganizationMemberController, :index, as: :member)
      post("/members", OrganizationMemberController, :create_invitation, as: :member)
      patch("/members/:invitation_id/cancel", OrganizationMemberController, :cancel_invitation, as: :member)
      delete("/members/:user_id/remove", OrganizationMemberController, :remove, as: :member)
      post("/check/:item", StartChecklistController, :check, as: :start_checklist)
    end

    get("/invitations/:invitation_id", OrganizationInvitationController, :show, as: :invitation)
    patch("/invitations/:invitation_id/accept", OrganizationInvitationController, :accept, as: :invitation)
    patch("/invitations/:invitation_id/refuse", OrganizationInvitationController, :refuse, as: :invitation)
  end

  scope "/heroku", AzimuttWeb do
    pipe_through([:api, :require_heroku_basic_auth])
    post("/resources", Api.HerokuController, :create)
    put("/resources/:resource_id", Api.HerokuController, :update)
    delete("/resources/:resource_id", Api.HerokuController, :delete)
  end

  scope "/heroku", AzimuttWeb do
    pipe_through([:browser_no_csrf_protection])
    if Azimutt.Application.env() == :dev, do: get("/", HerokuController, :index)
    post("/login", HerokuController, :login)
  end

  scope "/heroku", AzimuttWeb do
    pipe_through([:browser, :require_heroku_resource, :require_authed_user])
    get("/resources/:resource_id", HerokuController, :show)
  end

  scope "/clevercloud", AzimuttWeb do
    pipe_through([:api, :require_clever_cloud_basic_auth])
    post("/resources", Api.CleverCloudController, :create)
    put("/resources/:resource_id", Api.CleverCloudController, :update)
    delete("/resources/:resource_id", Api.CleverCloudController, :delete)
  end

  scope "/clevercloud", AzimuttWeb do
    pipe_through([:browser_no_csrf_protection])
    if Azimutt.Application.env() == :dev, do: get("/", CleverCloudController, :index)
    post("/login", CleverCloudController, :login)
  end

  scope "/clevercloud", AzimuttWeb do
    pipe_through([:browser, :require_clever_cloud_resource, :require_authed_user, AllowCrossOriginIframe])
    get("/resources/:resource_id", CleverCloudController, :show)
  end

  scope "/admin", AzimuttWeb, as: :admin do
    pipe_through([:browser, :require_authed_user, :require_admin_user, :admin_root_layout])
    get("/", Admin.DashboardController, :index)
    resources("/users", Admin.UserController, param: "user_id", only: [:index, :show])
    resources("/organizations", Admin.OrganizationController, param: "organization_id", only: [:index, :show])
    resources("/projects", Admin.ProjectController, param: "project_id", only: [:index, :show])
    resources("/events", Admin.EventController, param: "event_id", only: [:index, :show])
  end

  scope "/api/v1/swagger" do
    forward("/", PhoenixSwagger.Plug.SwaggerUI, otp_app: :azimutt, swagger_file: "swagger.json")
  end

  # public APIs
  scope "/api/v1", AzimuttWeb do
    pipe_through([:api])
    get("/gallery", Api.GalleryController, :index)
    get("/organizations/:organization_id/projects/:project_id", Api.ProjectController, :show)

backend/lib/azimutt/organizations/organization/data.ex
defmodule Azimutt.Organizations.Organization.Data do
  @moduledoc false
  use Ecto.Schema

  # see https://hexdocs.pm/ecto/embedded-schemas.html
  @primary_key false
  embedded_schema do
    field :allowed_layouts, :integer
    field :allowed_memos, :integer
    field :allow_table_color, :string
    field :allow_private_links, :boolean
    field :allow_database_analysis, :boolean
  end
end

backend/lib/azimutt_web/admin/organization/organization_controller.ex
defmodule AzimuttWeb.Admin.OrganizationController do
  use AzimuttWeb, :controller
  alias Azimutt.Admin
  alias Azimutt.Admin.Dataset
  alias Azimutt.Organizations
  alias Azimutt.Organizations.Organization
  alias Azimutt.Organizations.OrganizationPlan
  alias Azimutt.Tracking.Event
  alias Azimutt.Utils.Page
  action_fallback AzimuttWeb.FallbackController

  def index(conn, _params) do
    page = conn |> Page.from_conn(%{search_on: Organization.search_fields(), sort: "-created_at"})
    conn |> render("index.html", organizations: Admin.list_organizations(page))
  end

  def show(conn, %{"organization_id" => organization_id}) do
    now = DateTime.utc_now()
    events_page = conn |> Page.from_conn(%{prefix: "events", search_on: Event.search_fields(), sort: "-created_at", size: 40})
    {:ok, start_stats} = "2022-11-01" |> Timex.parse("{YYYY}-{0M}-{0D}")

    with {:ok, %Organization{} = organization} <- Admin.get_organization(organization_id),
         {:ok, %OrganizationPlan{} = plan} <- Organizations.get_organization_plan(organization, nil) do
      conn
      |> render("show.html",
        now: now,
        organization: organization,
        plan: plan,
        projects: organization.projects |> Enum.sort_by(& &1.updated_at, {:desc, Date}) |> Page.wrap(),
        members:
          organization.members
          |> Enum.sort_by(& &1.created_at, {:desc, Date})
          |> Enum.map(fn m -> m.user |> Azimutt.Repo.preload(:profile) end)
          |> Page.wrap(),
        invitations: organization.invitations |> Enum.sort_by(& &1.created_at, {:desc, Date}) |> Page.wrap(),
        activity:
          Dataset.chartjs_daily_data(
            [Admin.daily_organization_activity(organization) |> Dataset.from_values("Daily events")],
            start_stats,
            now
          ),
        events: Admin.get_organization_events(organization, events_page)
      )
    end
  end
end

backend/lib/azimutt_web/admin/organization/organization_view.ex
defmodule AzimuttWeb.Admin.OrganizationView do
  # use AzimuttWeb, :view
  # use Phoenix.View, root: "lib/azimutt_web/admin/templates", path: "*"
  use Phoenix.View, root: "lib/azimutt_web", namespace: AzimuttWeb
  import Phoenix.HTML.Tag
  import Phoenix.HTML.Link
  alias Azimutt.Organizations.Organization
  alias Azimutt.Services.StripeSrv
  alias Azimutt.Utils.Page
  alias AzimuttWeb.Router.Helpers, as: Routes

  def format_datetime(date) do
    {:ok, formatted} = Timex.format(date, "{Mshort} {D}, {h24}:{m}:{s}")
    formatted
  end

  def format_date_filter(date) do
    {:ok, formatted} = Timex.format(date, "{YYYY}-{0M}-{0D}")
    formatted
  end

  def format_data(data) when is_nil(data), do: ""
  def format_data(%Organization.Data{} = data), do: data |> Map.from_struct() |> Jason.encode!()

  def display_number(list) do
    threshold = Azimutt.config(:free_plan_seats)

    case Enum.count(list) do
      1 -> content_tag(:span, "1")
      x when x <= threshold -> content_tag(:span, x, class: "text-scheme-blue")
      x when x > threshold -> content_tag(:span, x, class: "text-scheme-red")
    end
  end
end

backend/lib/azimutt_web/controllers/api/organization_controller.ex
defmodule AzimuttWeb.Api.OrganizationController do
  use AzimuttWeb, :controller
  use PhoenixSwagger
  alias Azimutt.Organizations
  alias Azimutt.Organizations.Organization
  alias Azimutt.Services.TwitterSrv
  alias Azimutt.Tracking
  alias Azimutt.Utils.Result
  alias AzimuttWeb.Utils.CtxParams
  alias AzimuttWeb.Utils.SwaggerCommon
  action_fallback AzimuttWeb.Api.FallbackController

  swagger_path :index do
    tag("Organizations")
    summary("List user organizations")
    description("Get the list of all organizations the user is part of.")
    get("/organizations")
    SwaggerCommon.authorization()

    response(200, "OK", Schema.ref(:Organizations))
    response(400, "Client Error")
  end

  def index(conn, params) do
    current_user = conn.assigns.current_user
    ctx = CtxParams.from_params(params)
    organizations = Organizations.list_organizations(current_user)
    conn |> render("index.json", organizations: organizations, current_user: current_user, ctx: ctx)
  end

  def table_colors(conn, %{"organization_organization_id" => organization_id, "tweet_url" => tweet_url}) do
    now = DateTime.utc_now()
    current_user = conn.assigns.current_user

    with {:ok, %Organization{} = organization} <- Organizations.get_organization(organization_id, current_user),
         {:ok, %{user: _tweet_user, tweet: tweet_id}} <-
           TwitterSrv.parse_url(tweet_url) |> Result.map_error(fn _ -> {:bad_request, "Invalid tweet url"} end),
         {:ok, tweet} <- TwitterSrv.get_tweet(tweet_id) |> Result.map_error(fn e -> {:bad_request, e.message} end) do
      errors =
        [
          if(tweet |> TwitterSrv.Tweet.is_after?(now |> Timex.shift(minutes: -10)), do: nil, else: "Tweet not within the last 10 minutes"),
          if(tweet |> TwitterSrv.Tweet.has_mention?("azimuttapp"), do: nil, else: "Tweet doesn't mention @azimuttapp"),
          if(tweet |> TwitterSrv.Tweet.has_url?("https://azimutt.app"), do: nil, else: "Tweet doesn't link https://azimutt.app")
        ]
        |> Enum.filter(fn e -> e != nil end)

      if errors == [] do
        {:ok, _} = Organizations.allow_table_color(organization, tweet_url)
        Tracking.allow_table_color(current_user, organization, tweet_url)
      end

      conn |> render("table_colors.json", tweet: tweet, errors: errors)
    end
  end

  def swagger_definitions do
    %{
      Organization:
        swagger_schema do
          description("An Organization in Azimutt")

          properties do
            id(:string, "Unique identifier", required: true, example: "0ed17b9f-cb2c-403a-a148-03215b73deb4")
            slug(:string, "Organization slug", required: true, example: "azimutt")
            name(:string, "Organization name", required: true, example: "Azimutt")
            logo(:string, "Organization logo", example: "https://azimutt.app/images/logo_icon_dark.svg")
            description(:string, "Organization description", example: "The best database explorer for any database!")
          end
        end,
      Organizations:
        swagger_schema do
          description("A collection of Organizations")
          type(:array)
          items(Schema.ref(:Organization))
        end
    }
  end
end

backend/lib/azimutt_web/views/organization_view.ex
defmodule AzimuttWeb.OrganizationView do
  use AzimuttWeb, :view

  def last_update(datetime) do
    {:ok, relative_str} = datetime |> Timex.format("{relative}", :relative)
    relative_str
  end

  def generate_html_event_description(event) do
    %{text: text, author: author, destination: destination} = Azimutt.Tracking.event_to_action(event)

    content_tag :div, class: "text-xs" do
      [
        content_tag(:span, " #{author}", class: "font-semibold text-gray-900"),
        content_tag(:span, " #{text}", class: "text-gray-800"),
        content_tag(:span, " #{destination}", class: "font-semibold text-blue-500")
      ]
    end
  end
end

backend/lib/azimutt_web/templates/organization/_project_list_empty.html.heex
<div class="mt-12 max-w-lg mx-auto">
    <h2 class="text-xl leading-6 font-medium text-gray-900">Create your project</h2>
    <p class="mt-1 text-sm text-gray-500">You haven’t created a project yet. Get started by selecting a template or start from an empty project.</p>
    <ul role="list" class="mt-6 border-t border-b border-gray-200 divide-y divide-gray-200">
        <li>
            <div class="relative group py-4 flex items-start space-x-3">
                <div class="flex-shrink-0">
                    <span class="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-pink-500"><Icon.circle_stack kind="outline" class="text-white" /></span>
                </div>
                <div class="min-w-0 flex-1">
                    <div class="text-sm font-medium text-gray-900"><%= link "From database connection", to: Routes.elm_path(@conn, :orga_new, @organization, database: "") %></div>
                    <p class="text-sm text-gray-500">Extract your schema directly from your database connection.</p>
                </div>
                <div class="flex-shrink-0 self-center"><Icon.chevron_right class="text-gray-400 group-hover:text-gray-500" /></div>
            </div>
        </li>
        <li>
            <div class="relative group py-4 flex items-start space-x-3">
                <div class="flex-shrink-0">
                    <span class="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-purple-500"><Icon.document_text kind="outline" class="text-white" /></span>
                </div>
                <div class="min-w-0 flex-1">
                    <div class="text-sm font-medium text-gray-900"><%= link "From SQL structure", to: Routes.elm_path(@conn, :orga_new, @organization, sql: "") %></div>
                    <p class="text-sm text-gray-500">Upload your structure.sql file and let azimutt parse your schema.</p>
                </div>
                <div class="flex-shrink-0 self-center"><Icon.chevron_right class="text-gray-400 group-hover:text-gray-500" /></div>
            </div>
        </li>
        <li>
            <div class="relative group py-4 flex items-start space-x-3">
                <div class="flex-shrink-0">
                    <span class="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-yellow-500"><Icon.code_bracket kind="outline" class="text-white" /></span>
                </div>
                <div class="min-w-0 flex-1">
                    <div class="text-sm font-medium text-gray-900"><%= link "From JSON", to: Routes.elm_path(@conn, :orga_new, @organization, json: "") %></div>
                    <p class="text-sm text-gray-500">Import your custom source from JSON.</p>
                </div>
                <div class="flex-shrink-0 self-center"><Icon.chevron_right class="text-gray-400 group-hover:text-gray-500" /></div>
            </div>
        </li>
        <li>
            <div class="relative group py-4 flex items-start space-x-3">
                <div class="flex-shrink-0">
                    <span class="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-green-500"><Icon.document kind="outline" class="text-white" /></span>
                </div>
                <div class="min-w-0 flex-1">
                    <div class="text-sm font-medium text-gray-900"><%= link "Empty", to: Routes.elm_path(@conn, :orga_create, @organization, empty: "") %></div>
                    <p class="text-sm text-gray-500">Perfect to design your database from scratch!</p>
                </div>
                <div class="flex-shrink-0 self-center"><Icon.chevron_right class="text-gray-400 group-hover:text-gray-500" /></div>
            </div>
        </li>
        <li>
            <div class="relative group py-4 flex items-start space-x-3">
                <div class="flex-shrink-0">
                    <span class="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-blue-500"><Icon.squares_plus kind="outline" class="text-white" /></span>
                </div>
                <div class="min-w-0 flex-1">
                    <div class="text-sm font-medium text-gray-900"><%= link "Explore samples", to: Routes.elm_path(@conn, :orga_new, @organization, sample: "") %></div>
                    <p class="text-sm text-gray-500">Experiment Azimutt with suggested diagrams, for all tastes.</p>
                </div>
                <div class="flex-shrink-0 self-center"><Icon.chevron_right class="text-gray-400 group-hover:text-gray-500" /></div>
            </div>
        </li>
    </ul>
</div>

backend/lib/azimutt_web/templates/organization/billing.html.heex
<div class="mt-12 max-w-lg mx-auto">
    <h3 class="text-xl leading-6 font-medium text-gray-900">Organization billing</h3>
    <p class="mt-6 text-sm text-gray-500">
        Thank you so much for supporting us. It's really great for us to be an open source project and have a community supporting us with paying plans ✨
    </p>
    <p class="mt-3 text-sm text-gray-500">
        Azimutt partner with Stripe to handle subscriptions, you can manage it with the link below. You can cancel your subscription anytime.
    </p>
    <%= link "Manage your subscription", to: Routes.organization_billing_path(@conn, :edit, @organization.id), method: :post, class: "mt-6 inline-flex items-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:text-sm" %>
</div>